be/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stuprobe.urls')),
    path('stuprobe/', include('stuprobe.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='stuprobe/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name='stuprobe/logout.html'), name='logout'),

]

stuprobe/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('student/<slug:stud_id>/attendance/', views.attendance, name='attendance'),
    path('student/<slug:stud_id>/<slug:course_id>/attendance/', views.attendance_detail, name='attendance_detail'),
    path('student/<slug:class_id>/timetable/', views.timetable, name='timetable'),
   
    path('t_form/<slug:assign_id>', views.t_form, name='t_form'),
    path('upload/<slug:assign_id>', views.t_upload, name='t_upload'),
    path('teacher/<slug:teacher_id>/Classes/', views.t_clas, name='t_clas'),
    path('teacher/<int:assign_id>/Students/attendance/', views.t_student, name='t_student'),
    path('teacher/<int:ass_c_id>/attendance/', views.t_attendance, name='t_attendance'),
    path('teacher/<slug:stud_id>/<slug:course_id>/attendance/', views.t_attendance_detail, name='t_attendance_detail'),
    path('teacher/<int:att_id>/change_attendance/', views.change_att, name='change_att'),
    path('teacher/<slug:teacher_id>/t_timetable/', views.t_timetable, name='t_timetable'),
    
    path('form/', views.form, name='form'),
    path('studentupload/<slug:stud_id>', views.s_upload, name='s_upload'),

    path('signup/<slug:role>/', views.signup, name='signup'),
    path('home/', views.home, name='home'), 

]

stuprobe/models.py
import math

from datetime import timedelta, date

from django.db import models
from django.contrib.auth.models import AbstractUser



# Create your models here.

time_slots = (
    ('10:00 - 10:55', '10:00 - 10:55'),
    ('10:55 - 11:50', '10:55 - 11:50'),
    
    ('12:35 - 1:30', '12:35 - 1:30'),
    ('1:30 - 2:25', '1:30 - 2:25'),
    
    ('2:45 - 3:40', '2:45 - 3:40'),
    ('3:40 - 4:45', '3:40 - 4:45'),
)

DAYS_OF_WEEK = (
    ('Monday', 'Monday'),
    ('Tuesday', 'Tuesday'),
    ('Wednesday', 'Wednesday'),
    ('Thursday', 'Thursday'),
    ('Friday', 'Friday'),
    ('Saturday', 'Saturday'),
)



class User(AbstractUser):
    @property
    def is_student(self):
        if hasattr(self, 'student'):
            return True
        return False

    @property
    def is_teacher(self):
        if hasattr(self, 'teacher'):
            return True
        return False


class Dept(models.Model):
    id = models.CharField(primary_key='True', max_length=100)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Course(models.Model):
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
    id = models.CharField(primary_key='True', max_length=50)
    name = models.CharField(max_length=50)
    shortname = models.CharField(max_length=50, default='X')

    def __str__(self):
        return self.name


class Class(models.Model):
    id = models.CharField(primary_key='True', max_length=100)
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
    section = models.CharField(max_length=100)
    sem = models.IntegerField()

    class Meta:
        verbose_name_plural = 'classes'

    def __str__(self):
        d = Dept.objects.get(name=self.dept)
        return '%s : %d %s' % (d.name, self.sem, self.section)


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    class_id = models.ForeignKey(Class, on_delete=models.CASCADE, default=1)
    GRN = models.CharField(primary_key='True', max_length=100)
    name = models.CharField(max_length=200)
   

    def __str__(self):
        return self.name


class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    id = models.CharField(primary_key=True, max_length=100)
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Assign(models.Model):
    class_id = models.ForeignKey(Class, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('course', 'class_id', 'teacher'),)

    def __str__(self):
        cl = Class.objects.get(id=self.class_id_id)
        cr = Course.objects.get(id=self.course_id)
        te = Teacher.objects.get(id=self.teacher_id)
        return '%s : %s : %s' % (te.name, cr.shortname, cl)


class AssignTime(models.Model):
    assign = models.ForeignKey(Assign, on_delete=models.CASCADE)
    period = models.CharField(max_length=50, choices=time_slots, default='11:00 - 11:50')
    day = models.CharField(max_length=15, choices=DAYS_OF_WEEK)




class Attendance(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    date = models.DateField(default='2018-10-23')
    status = models.BooleanField(default='True')

    def __str__(self):
        sname = Student.objects.get(name=self.student)
        cname = Course.objects.get(name=self.course)
        return '%s : %s' % (sname.name, cname.shortname)


class AttendanceTotal(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('student', 'course'),)

    @property
    def att_class(self):
        stud = Student.objects.get(name=self.student)
        cr = Course.objects.get(name=self.course)
        att_class = Attendance.objects.filter(course=cr, student=stud, status='True').count()
        return att_class

    @property
    def total_class(self):
        stud = Student.objects.get(name=self.student)
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(course=cr, student=stud).count()
        return total_class

    @property
    def attendance(self):
        stud = Student.objects.get(name=self.student)
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(course=cr, student=stud).count()
        att_class = Attendance.objects.filter(course=cr, student=stud, status='True').count()
        if total_class == 0:
            attendance = 0
        else:
            attendance = round(att_class / total_class * 100, 2)
        return attendance

stuprobe/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from stuprobe.models import *


class UserRegForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')
    
    def save(self, commit=True):
        user = super(UserRegForm,self).save()
        return user

class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ('class_id','GRN','name')

    def save(self, commit=True):
        user = super(StudentForm,self).save()
        return user


class TeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = ('id', 'dept','name')

    def save(self, commit=True):
        user = super(TeacherForm,self).save()
        return user

stuprobe/views.py
import os, shutil



from os import path
from django.core import serializers
from django.urls import reverse
from django.utils import timezone

from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect


from .models import *
from stuprobe.forms import *



reg_save = 'C:/project/be/data/registered/'
classroom_save = 'C:/project/be/data/classroom_uploads/'



# Create your views here.
def index(request):
    return render(request, 'stuprobe/logout.html')


def signup(request, role):
    if role == 'student':
        if request.method == 'POST':
            user_form = UserRegForm(request.POST)
            student_form = StudentForm(request.POST)

            if user_form.is_valid() and student_form.is_valid():
                user = user_form.save()
                student = student_form.save(False)

                student.user = user
                student.save()

                return render(request, 'stuprobe/base.html')

        else:
            user_form = UserRegForm()
            student_form = StudentForm()
        context = {
            'UserForm' : user_form,
            'StudentForm' : student_form,
            'role' : role
        }
        return render(request, 'stuprobe/signup.html', context )

    else:
        if request.method == 'POST':
            user_form = UserRegForm(request.POST)
            teacher_form = TeacherForm(request.POST)
            if user_form.is_valid() and teacher_form.is_valid():
                user = user_form.save()
                teacher = teacher_form.save(False)

                teacher.user = user
                teacher.save()

                return render(request, 'stuprobe/base.html')

        else:
            user_form = UserRegForm()
            teacher_form = TeacherForm()

        context = {
            'UserForm' : user_form,
            'TeacherForm' : teacher_form,
            'role' : role
        }
        return render(request, 'stuprobe/signup.html', context )





@login_required
def home(request):
    if request.user:
        return render(request, 'stuprobe/homepage.html')
    return render(request, 'stuprobe/logout.html')


@login_required()
def attendance(request, stud_id):
    stud = Student.objects.get(GRN=stud_id)
    ass_list = Assign.objects.filter(class_id_id=stud.class_id)
    att_list = []
    for ass in ass_list:
        try:
            a = AttendanceTotal.objects.get(student=stud, course=ass.course)
        except AttendanceTotal.DoesNotExist:
            a = AttendanceTotal(student=stud, course=ass.course)
            a.save()
        att_list.append(a)
    return render(request, 'stuprobe/attendance.html', {'att_list': att_list})


@login_required()
def attendance_detail(request, stud_id, course_id):
    stud = get_object_or_404(Student, GRN=stud_id)
    cr = get_object_or_404(Course, id=course_id)
    att_list = Attendance.objects.filter(course=cr, student=stud).order_by('date')
    att_list_graph = Attendance.objects.only("date", "status")
    att_list_graph = serializers.serialize('json', att_list_graph)


    context = {
        'att_list': att_list,
        'cr': cr,
        'json':att_list_graph,
    }
    return render(request, 'stuprobe/att_detail.html', context)










@login_required
def t_clas(request, teacher_id):
    teacher1 = get_object_or_404(Teacher, id=teacher_id)
    return render(request, 'stuprobe/t_clas.html', {'teacher1': teacher1})


@login_required()
def t_student(request, assign_id):
    ass = Assign.objects.get(id=assign_id)
    att_list = []
    for stud in ass.class_id.student_set.all():
        try:
            a = AttendanceTotal.objects.get(student=stud, course=ass.course)
        except AttendanceTotal.DoesNotExist:
            a = AttendanceTotal(student=stud, course=ass.course)
            a.save()
        att_list.append(a)
    return render(request, 'stuprobe/t_students.html', {'att_list': att_list})



@login_required()
def t_attendance(request, ass_c_id):
    assc = get_object_or_404(AttendanceClass, id=ass_c_id)
    ass = assc.assign
    c = ass.class_id
    context = {
        'ass': ass,
        'c': c,
        'assc': assc,
    }
    return render(request, 'stuprobe/t_attendance.html', context)




@login_required()
def t_attendance_detail(request, stud_id, course_id):
    history = []
    stud = get_object_or_404(Student, GRN=stud_id)
    cr = get_object_or_404(Course, id=course_id)
    att_list = Attendance.objects.filter(course=cr, student=stud).order_by('date')
    for a in att_list:
        if a.status:
            print(a.status)
            history.append(1)
        else:
            print(a.status)
            history.append(0)
    return render(request, 'stuprobe/t_att_detail.html', {'att_list': att_list, 'cr': cr, 'history':history})


@login_required()
def change_att(request, att_id):
    a = get_object_or_404(Attendance, id=att_id)
    a.status = not a.status
    a.save()
    return HttpResponseRedirect(reverse('t_attendance_detail', args=(a.student.GRN, a.course_id)))





@login_required()
def timetable(request, class_id):
    asst = AssignTime.objects.filter(assign__class_id=class_id)
    matrix = [['' for i in range(9)] for j in range(6)]

    for i, d in enumerate(DAYS_OF_WEEK):
        t = 0
        for j in range(9):
            if j == 0:
                matrix[i][0] = d[0]
                continue
            if j == 3 or j == 6:
                continue
            try:
                a = asst.get(period=time_slots[t][0], day=d[0])
                matrix[i][j] = a.assign.course_id
            except AssignTime.DoesNotExist:
                pass
            t += 1

    context = {'matrix': matrix}
    return render(request, 'stuprobe/timetable.html', context)


@login_required()
def t_timetable(request, teacher_id):
    asst = AssignTime.objects.filter(assign__teacher_id=teacher_id)
    class_matrix = [[True for i in range(9)] for j in range(6)]
    for i, d in enumerate(DAYS_OF_WEEK):
        t = 0
        for j in range(9):
            if j == 0:
                class_matrix[i][0] = d[0]
                continue
            if j == 3 or j == 6:
                continue
            try:
                a = asst.get(period=time_slots[t][0], day=d[0])
                class_matrix[i][j] = a
            except AssignTime.DoesNotExist:
                pass
            t += 1

    print(class_matrix)
    context = {
        'class_matrix': class_matrix,
    }
    return render(request, 'stuprobe/t_timetable.html', context)


###################___________UPLOAD FORM VIEWS___________#######################
def form(request):
    return render(request, "stuprobe/form.html")



def t_form(request, assign_id):
    print('######################################')
    
    
    for filename in os.listdir(classroom_save):
        file_path = os.path.join(classroom_save, filename)
        print(file_path)
        try:
            if os.path.isdir(file_path):
                shutil.rmtree(file_path)
        except Exception as e:
            print('Failed to delete %s. Reason: %s' % (file_path, e))
    return render(request, "stuprobe/form.html", {'assign_id':assign_id})



def t_upload(request, assign_id):

    


    
    course_name = get_object_or_404(Assign, id=assign_id)
    course_id = course_name.course_id
    
    

    if not path.exists(classroom_save + course_id + '/'):
	    os.mkdir(classroom_save + course_id + '/')

    for count, x in enumerate(request.FILES.getlist("files")):
        def process(f):
            with open(classroom_save + course_id + '/' + str(count) + '.jpg', 'wb+') as destination:
                for chunk in f.chunks():
                    destination.write(chunk)
        process(x)
    return render(request, 'stuprobe/message.html')




def s_upload(request, stud_id):
    if not path.exists(reg_save + stud_id + '/'):
        os.mkdir(reg_save + stud_id + '/')
    
    for count, x in enumerate(request.FILES.getlist("files")):
        def process(f):
            with open(reg_save + stud_id + '/' + str(count) + '.jpg', 'wb+') as destination:
                for chunk in f.chunks():
                    destination.write(chunk)
        process(x)
    return render(request, 'stuprobe/message.html')

stuprobe/templates/stuprobe/att_detail.html
{% extends 'stuprobe/base.html' %} 
{% load static %}

{% block head %}
<script src="{% static '/stuprobe/scripts/pred.js' %}"></script>
{% endblock %}
{% block content %}

<b>{{ cr.name }}</b>
<div class="card">
    <table width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>#</th>
                <th>Date</th>
                <th>Day</th>
                <th>Status</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for a in att_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ a.date }}</td>
                <td>{{ a.date|date:"l" }}</td>
                {% if a.status %}
                <td class="success">Present</td>
                {% else %}
                <td class="danger">Absent</td>
        {% endif %}
    </tr>
    {% empty %}
    <p>student has no attendance</p>
    {% endfor %}
    </tbody>
    </table>
</div>

{% endblock %}

stuprobe/templates/stuprobe/attendance.html
{% extends 'stuprobe/base.html' %}
{% block content %}

<b>Attendance</b>
<div class="card">
   <table width="100%" cellspacing="0">
      <thead>
         <tr>
            <th>Course ID</th>
            <th>Course name</th>
            <th>Attended classes</th>
            <th>Total classes</th>
            <th>Attendance %</th>

         </tr>
      </thead>
      <tbody>
         {% for a in att_list %}
         <tr>
            <td>{{ a.course_id }}</td>
            <td><a class="link" href="{% url 'attendance_detail' a.student.GRN a.course.id %}">{{a.course.name}}</a></td>
            <td>{{ a.att_class }}</td>
            <td>{{ a.total_class }}</td>
            {% if a.attendance < 75 %}
            <td class="danger">{{ a.attendance }}</td>
            {% else %}
            <td class="success">{{ a.attendance }}</td>
            {% endif %}
            
         </tr>
         {% empty %}
         <p>student has no courses</p>
         {% endfor %}
      </tbody>
   </table>
   
</div>
{% endblock %}

stuprobe/templates/stuprobe/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      {% if title %}
        <title>Stuprobe - {{ title }}</title>
      {% else %}
        <title>Stuprobe</title>
      {% endif %}

      <link href="{% static '/stuprobe/css/custom.css' %}" rel="stylesheet">
      {% block head %}
      {% endblock %}
   </head>
   <body>
      <nav>
         <div class="nav-logo">
            <a href="{% url 'home' %}">Stuprobe</a>
         </div>
         <div class="nav-end">
            <div class="nav-username">
               {% if request.user.is_student %}
               <item>
                  <span>{{request.user.student.name}}</span>
               </item>
               {% elif request.user.is_teacher %}
               <item>
                  <span>{{request.user.teacher.name}}</span>
               </item>
               {% endif %}
               <a class="logout" href="/accounts/logout">
                  Logout
               </a>
            </div>
         </div>       
      </nav>
      <div class="main-grid">
         <aside>
            
               {% if request.user.is_student %}
               
                  <a href="{% url 'attendance' request.user.student.GRN %}">
                  <span>Attendance</span>
                  </a>
               
              
            
                  <a href="{% url 'timetable' request.user.student.class_id_id %}">
                  <span>Time Table</span>
                  </a>
              
               {% elif request.user.is_teacher %}
               
                  <a href="{% url 't_clas' request.user.teacher.id %}">
                  <span>Attendance</span>
                  </a>
              
         
                  <a href="{% url 't_timetable' request.user.teacher.id %}">
                  <span>Time Table</span>
                  </a>
             
               {% endif %}
          
         </aside>
   
         <div class="content-padding">
            <div>
               
               {% block content %}
               {% endblock %}
            </div>
            
         </div>
      </div>

      
   </body>
</html>

stuprobe/templates/stuprobe/form.html
{% extends 'stuprobe/base.html' %}

{% block head %}
    <script>
        function previewFiles() {

        var preview = document.querySelector('#preview');
        var files   = document.querySelector('input[type=file]').files;

        function readAndPreview(file) {

        
        if ( /\.(jpe?g|png|gif)$/i.test(file.name) ) {
            var reader = new FileReader();

            reader.addEventListener("load", function () {
            var image = new Image();
            image.height = 100;
            image.title = file.name;
            image.src = this.result;
            preview.appendChild( image );
            }, false);

            reader.readAsDataURL(file);
        }

        }

        if (files) {
        [].forEach.call(files, readAndPreview);
        }

        }
    </script>
    <style>
        #preview{
            display: grid;
            grid-gap: 5px;
            grid-template-columns: repeat(5,100px) ;
            margin-top: 50px;
            overflow: auto;
        }
        img{
            width: 100px;
        }
    </style>

{% endblock %}


{% block content %}


{% if request.user.is_student %}
Upload your image(s)
<i>Atleast 3 recommended</i>
<form method="post" action="{% url 's_upload' request.user.student.GRN %}" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="files" onchange="previewFiles()" multiple/>
    <input type="submit" value="Upload"/>
</form>
<div id="preview"></div>
{% else %}


Upload classroom lecture image(s)
<form method="post" action="{% url 't_upload' assign_id %}" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="files" onchange="previewFiles()" multiple/>
    <input type="submit" value="Upload"/>
</form>
<div id="preview"></div>
{% endif %}

{% endblock %}

stuprobe/templates/stuprobe/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>Homepage</title>
      <link href="{% static '/stuprobe/css/custom.css' %}" rel="stylesheet">
   </head>
   <body>
      <nav>
         <div class="nav-logo">
            <a href="{% url 'home' %}">Stuprobe</a>
         </div>
         <div class="nav-end">
            <div class="nav-username">
               {% if request.user.is_student %}
               <item>
                  <span>{{request.user.student.name}}</span>
               </item>
               {% elif request.user.is_teacher %}
               <item>
                  <span>{{request.user.teacher.name}}</span>
               </item>
               {% endif %}
               <a class="logout" href="/accounts/logout">
                  Logout
               </a>
            </div>
         </div>       
      </nav>
      
      <div class="main-grid">
         <div class="welcome-msg">
            <div>Welcome,</div> 
            {% if request.user.is_student %}
            <b>{{ request.user.student.name }}</b>
            {% elif request.user.is_teacher %}
            <b>{{ request.user.teacher.name }}</b>
            {% endif %}
         </div>
         


         <div class="content-grid">
               <div class="card">
                  {% if request.user.is_student %}
                  <a href="{% url 'attendance' request.user.student.GRN %}">
                  {% elif request.user.is_teacher %}
                  <a href="{% url 't_clas' request.user.teacher.id %}">
                  {% endif %}
                  <img width="100px" height="100px" class="card-img-top" src="{% static 'stuprobe/images/attendance.png' %}" alt="attendance-image">
                  </a>
                  <div>
                     <b>Attendance</b>
                     <p>View the attendance status for each of your courses. The attendance of each course is
                        also displayed as list of classes that were conducted.
                     </p>
                  </div>
                  <div>
                     {% if request.user.is_student %}
                     <a class="btn" role="button" href="{% url 'attendance' request.user.student.GRN %}"> View Attendance</a>
                     {% elif request.user.is_teacher %}
                     <a class="btn" role="button" href="{% url 't_clas' request.user.teacher.id %}">Attendance</a>
                     {% endif %}
                  </div>
               </div>

            
               <div class="card">
                  {% if request.user.is_student %}
                  <a href="{% url 'timetable' request.user.student.class_id_id %}">
                  {% elif request.user.is_teacher %}
                  <a href="{% url 't_timetable' request.user.teacher.id %}">
                  {% endif %}
                  <img width="130px" height="100px" src="{% static 'stuprobe/images/timetable.png' %}" alt="time-table-image">
                  </a>
                  <div>
                     <b>TimeTable</b>
                     <p>View the timetable in a tabular form. The timetable displays all the courses of the
                        student and the time and day at which they are conducted.
                     </p>
                  </div>
                  <div>
                     {% if request.user.is_student %}
                     <a class="btn" role="button" href="{% url 'timetable' request.user.student.class_id_id %}">View TimeTable</a>
                     {% elif request.user.is_teacher %}
                     <a class="btn" role="button" href="{% url 't_timetable' request.user.teacher.id %}">View TimeTable</a>
                     {% endif %}
                  </div>
               </div>
           
            {% if request.user.is_student %}
            
               <div>
                  <div>
                     <b>Register Images</b>
                     <p>Register your images <i>(Works only once!)</i> , please do it once and correctly.</p>
                  </div>
                  <div>
                     <a class="btn" role="button" href="{% url 'form' %}">Register</a>
                  </div>
               </div>
            
            {% endif %}
         </div>
      </div>
   </div>
      </div>
      
   </body>
</html>

stuprobe/templates/stuprobe/login.html
{% load static %}
{% load crispy_forms_tags  %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   
    <title>Login</title>


    <link href="{% static '/stuprobe/css/custom.css' %}" rel="stylesheet">

  </head>

  <body>
    <nav>
      <div class="nav-logo">
        <a href="{% url 'index' %}">Stuprobe</a>
     </div>
    </nav>
    <div class="flex-card bg">
      <span class="shadow">
        <b>Login</b> 
        <form method="post">
          {% csrf_token %}
          {{ form|crispy}}
          <button  class="btn" type="submit">Login</button>
        </form>
      </span>
      
    </div>

   

  </body>

</html>

stuprobe/templates/stuprobe/logout.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">
      <title>Login</title>
      {% load static %}
      <link href="{% static '/stuprobe/css/custom.css' %}" rel="stylesheet">
   </head>
   <body>
      <nav>
         <div class="nav-logo">
            <a href="{% url 'index' %}">Stuprobe</a>
         </div>
      </nav>
      <div class="main-grid">
         
         <b class="welcome-msg">Welcome to Stuprobe!</b>
         
         <div class="content-grid">
            
               <div class="card bg">
                  <h3>Login to Stuprobe</h3>
                  <div class="">
                     <a class="btn btn-primary" role="button" href="/home">Login</a>
                  </div>
               </div>
            
            
               <div class="card bg">
                  <h3>Signup as a <b>Student</b></h3>
                  <div class="">
                     <a class="btn btn-primary" role="button" href="/signup/student">Sign Up</a>
                  </div>
               </div>
           
               <div class="card bg">
                  <h3>Signup as a <b>Teacher</b></h3>
                  <div class="">
                     <a class="btn btn-primary" role="button" href="/signup/teacher">Sign Up</a>
                  </div>
               </div>
            
         </div>
      </div>
   </body>
</html>

stuprobe/templates/stuprobe/message.html
{% extends 'stuprobe/base.html' %}
{% block content %}

<b>Files uploaded</b>
<a class="link" href="{% url 'home' %}">Go to Home</a>
<i>Kindly wait at least 10 minutes before <b>entering attendance</b> again</i>

{% endblock %}

stuprobe/templates/stuprobe/t_clas.html
{% extends 'stuprobe/base.html' %}
{% block content %}
    <b>List of Classes</b>
    <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered text-center" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                        <th>Class</th>
                        <th>Course</th>
                        <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for ass in teacher1.assign_set.all %}
                    <tr>
                        <td>{{ ass.class_id }}</td>
                        <td>{{ ass.course }}</td>
                        <td>
                          <a class="btn" href="{% url 't_form' ass.id %}" role="button">Enter Attendance</a>
                            <a class="btn" href="{% url 't_student' ass.id %}">View Students</a>
                        </td>
                    </tr>
                    {% empty %}
                            <p>teacher has no courses</p>
                    {% endfor %}

                  </tbody>
                </table>
              </div>
    </div>
{% endblock %}

stuprobe/templates/stuprobe/t_students.html
{% extends 'stuprobe/base.html' %}
{% load static %}
{% block content %}

<b>Attendance</b>
<div class="card">
   <table width="100%" cellspacing="0">
      <thead>
         <tr>
            <th>GRN</th>
            <th>Student name</th>
            <th>Attended classes</th>
            <th>Total classes</th>
            <th>Attendance %</th>
         </tr>
      </thead>
      <tbody>
         {% for a in att_list %}
         <tr>
            <td>{{ a.student_id }}</td>
            <td><a class="link" href="{% url 't_attendance_detail' a.student.GRN a.course_id %}">{{ a.student.name }}</a></td>
            <td>{{ a.att_class }}</td>
            <td>{{ a.total_class }}</td>
            {% if a.attendance < 75 %}
            <td class="danger">{{ a.attendance }}</td>
            {% else %}
            <td class="success">{{ a.attendance }}</td>
            {% endif %}
         </tr>
         {% empty %}
         <p>No students</p>
         {% endfor %}
      </tbody>
   </table>
</div>
{% endblock %}